server:
  port: 8080

spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
      suffix: .html
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    converters:
      preferred-json-mapper: fastjson
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath*:com/jfeat/**/mapping/*.xml
  typeAliasesPackage: com.jfeat.**.model
  global-config:
    id-type: 2  #0:数据库ID自增   1:用户输入id   2:全局唯一id(IdWorker)   3:全局唯一ID(uuid)  4: 该类型为未设置主键类型(none)
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 1
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

xxl:
  job:
    accessToken: 1fa8b0dac0088609fe3418998281c54a0785a6e7d1b5b80976ff22110110a1d7bc773d1b555c5618e33996aaf8639b8a94fbdfd01aa44cbebba1456a035b10ac
    admin:
      addresses: http://127.0.0.1:8181/schedule-job-admin
    executor:
      appid: 2
      address: ''
      appname: nft-oms
      ip: ''
      logretentiondays: 30
      port: 9999
      logpath: ./log/xxl-job/jobhandler


###################  jwt配置  ###################
jwt:
  encoded-key: L7A/6zARSkK1j7Vd5SDD9pSSqZlqF7mAhiOgRbgv9Smce6tf4cJnvKOjtKPxNNnWQj+2lQEScm3XIUjhW+YVZg==
  normal-encoded-key: bm9ybWFsLWVuY29kZWQta2V5
################### io config ##################
io:
  excel-template-dir: "templates"
  ################### file upload config ##################
  file-upload-path: /webapps/images
  file-host: /images
  ################### sms config ##################
  sms:
    enableVendor: weiwebs
    captchaRequiredOperations:
      - login
      - register
      - changeAccount
      - findPassword
      - matchSucceed
      - successful
    vendors:
      weiwebs:
        captchaCount: 5
        captchaTtlSeconds: 120
        templates:
          - operation: login
            templateContent: '【元咕咕】您的短信验证码是：{code}，2分钟内有效'
            templateParam: '{"code": "%s"}'
          - operation: register
            templateContent: '【元咕咕】您的短信验证码是：{code}，2分钟内有效'
            templateParam: '{"code": "%s"}'
          - operation: findPassword
            templateContent: '【元咕咕】您的短信验证码是：{code}，2分钟内有效'
            templateParam: '{"code": "%s"}'
          - operation: changeAccount
            templateContent: '【元咕咕】您正在修改信息，短信验证码是：{code}，2分钟内有效'
            templateParam: '{"code": "%s"}'
          - operation: matchSucceed
            templateContent: '【元咕咕】恭喜您匹配成功，请在2小时内登录进行处理'
          - operation: successful
            templateContent: '【元咕咕】恭喜您对方已经完成处理，请您即刻登录核实'
        account: MXT801633
        pswd: Mxt801636
        url: http://www.weiwebs.cn/msg/HttpBatchSendSM
      venus:
        captchaCount: 5
        captchaTtlSeconds: 120
        templates:
          - operation: login
            templateContent: '【元咕咕】您的短信验证码是：{code}，2分钟内有效'
            templateParam: '{"code": "%s"}'
          - operation: register
            templateContent: '【元咕咕】您的短信验证码是：{code}，2分钟内有效'
            templateParam: '{"code": "%s"}'
          - operation: changeAccount
            templateContent: '【元咕咕】您正在修改信息，短信验证码是：{code}，2分钟内有效'
            templateParam: '{"code": "%s"}'
          - operation: matchSucceed
            templateContent: '【元咕咕】恭喜您匹配成功，请在2小时内登录进行处理'
          - operation: successful
            templateContent: '【元咕咕】恭喜您对方已经完成处理，请您即刻登录核实'
        account: VIP322
        password: 322223
        userId: 33346
        url: http://123.57.51.191:8888/sms.aspx
      aliyun:
        captchaCount: 5
        captchaTtlSeconds: 120
        templates:
          - operation: login
            signName: aliyun
            templateContent: 'aliyun not use this field'
            templateParam: '{"code": "%s"}'
            templateCode: T1
        accessKeyId: keyid
        accessSecret: secret
  ###################  找回密码配置  ###################
  email:
    project: Zero Crud
    outTime: 30
    resetUrlEnd: http://127.0.0.1:8080/api/pub/password/normal/resetPassword
    resetUrlFront: http://127.0.0.1:8080/#/resetPwd
    loginUrl: http://console.smallsaas.cn/login

###################  aliyun-hub ###################
aliyun:
  sms:
    enable: true
    signName: "星鱼科技"
    accessKeyId: ""
    accessSecret: ""
    createPlan: "SMS_203677187"
    createOrder: "SMS_203677196"
    deliverTask: "SMS_203677243"
    taskDeadLine: "SMS_203677248"
    taskUpload: "SMS_203677255"
    registration: "SMS_203820167"
---

spring:
  profiles: dev
  datasource:
#    url: jdbc:mysql://localhost:3306/nft_test?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    url: jdbc:mysql://sh-cdb-q5vnc0iy.sql.tencentcdb.com:59449/nft_prod?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: zb2014@888
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: log4j,wall,mergeStat
    sql-script-encoding: UTF-8
    schema: classpath*:sql/**/*-schema.sql
    data: classpath*:sql/**/*-data.sql
    initialize: false

logging:
  level: error
  file: target/logs/access.log

management:
  info:
    git:
      mode: simple  #项目git版本信息展示 full 展示信息多 simple 展示信息少

toggle:
  taskEnable: true
---
