@local = http://localhost:8080
@player1 = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6MzksImFjY291bnQiOiJhY2M2MzQ1MTg5MCIsImRvbWFpblVzZXJJZCI6MzgsImlhdCI6MTY0MzA5ODEzMSwianRpIjoiMzkiLCJzdWIiOiJhY2M2MzQ1MTg5MCIsImV4cCI6MTY0MzM1NzMzMX0.RoOWH2ecWQOgFbe4vxhfdr91hAKNeEbMY48SzSEyyUcnMN4JMG7sq8zo5S0BsAOExIYwCss1tm9neTClHKzyTw

### 玩家登陆
POST {{local}}/api/app/oauth/player/login

{
    "account": "18933934127",
    "password": "a123456"
}

### 修改玩家支付密码
POST {{local}}/api/u/player/paymentPassword/change
Authorization: {{player1}}

{
  "newPaymentPassword": "54321",
  "verifyCode": "string"
}

### 卖家确认
POST {{local}}/api/u/order/wisp/164/confirmReceived
Authorization: {{player1}}

{
    "paymentPassword":"111111"
}