@endpoint = http://api.dev.smallsaas.cn:8084
@local = http://localhost:8080
@manage = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjoyLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDIyMzUwODEsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MjQ5NDI4MX0.eyUbNk8ZFg-xJAMNosSHIlnJo5rjCo_-Jtfvx8cuOnVEzuJqBvOuOBK6MGSlw5xmaCf72y8aMKIgqLPcTGbAGQ
@player = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6MSwidXNlcklkIjo1OTcsImFjY291bnQiOiJhY2MxMzM0MTc3MCIsImRvbWFpblVzZXJJZCI6Mzc3LCJpYXQiOjE2NDI0OTcyNzAsImp0aSI6IjU5NyIsInN1YiI6ImFjYzEzMzQxNzcwIiwiZXhwIjoxNjQyNzU2NDcwfQ.pZUx7Kx6h4w9_ZrGMMqaOM7QNK5zI-smrscdEfNosQHGAcPyebDw0F8GGvMmEH5-arcC37oQPjNiE4xuc3mS9Q
@admin= Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDMwNzYxNjMsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MzMzNTM2M30.lO0hgdgjeEuYoyhH0oUttf7m7kKRcZGuVdbb5Jgm5pRtuuZaxxF4EhfYFfiq8ZaCU7GOxI3hT-v5HwBQpqpPyg

### 管理员登陆
POST {{endpoint}}/api/sys/oauth/login
Authorization: {{admin}}

{
    "account": "admin",
    "password": "111111",
    "verifyCode": "验证码"
}

### 管理员登陆（本地）
POST {{endpoint}}/api/sys/oauth/login
Content-Type: application/json

{
    "account": "admin",
    "password": "111111",
    "verifyCode": "验证码"
}

### 添加管理员
POST {{endpoint}}/api/adm/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidXNlclR5cGUiOjEwMSwiYlVzZXJUeXBlIjoiU1lTVEVNIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsImV4dHJhVXNlclR5cGUiOjAsImlhdCI6MTY0MDY3MzY3MiwianRpIjoiMSIsInN1YiI6ImFkbWluIiwiZXhwIjoxNjQwOTMyODcyfQ.ak0ebRv-Aaf35FQDE2NeobJ73o3kAe-_mZ0XI8vzznrnSpmSl1K7dcK3UJOm3AvjnZW8K5F5li-ffQ8HUm3qgg

{
  "account": "manage3",
  "name": "店小二5",
  "orgId": "1",
  "password": "manage3",
  "phone": "15322325901"
}

### 管理员登陆
POST {{endpoint}}/api/sys/oauth/login

{
    "account": "myTest",
    "password": "admin",
    "verifyCode": "验证码"
}

### 玩家注册
POST {{endpoint}}/api/app/oauth/player/register

{
    "name": "绘梨衣",
    "phone": "15322315902",
    "verifyCode": "83235",
    "loginPassword": "a13245235_",
    "invitationCode": "2joquu"
}


### 玩家登陆(路明非)
POST {{endpoint}}/api/app/oauth/player/login

{
    "account": "15322315902",
    "password": "Admin1234!",
    "verifyCode":"9963"
}


### 玩家登陆(绘梨衣)
POST {{local}}/api/app/oauth/player/login

{
"account":"15322315902",
"password":"a13245235_"
}

### 玩家登陆(楚子航)
POST {{endpoint}}/api/app/oauth/player/login

{
"account":"13800000009",
"password":"a123456"
}

### 玩家登陆(路明泽)
POST {{local}}/api/app/oauth/player/login
Content-Type: application/json

{
"account":"15322315901",
"password":"admin"
}


### ym
POST {{endpoint}}/api/app/oauth/player/login
Content-Type: application/json

{
"account":"13925814700",
"password":"aa123456"
}

### 转
POST {{local}}/api/u/player/transferCoins
Authorization: {{player}}

{
    "number":"100",
    "targetPlayerMobilePhone":"13560432148",
    "paymentPassword":"123456"
}

### 转让GuGu令
@token = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6NTksImFjY291bnQiOiJhY2MxNDg3NzA1NCIsImRvbWFpblVzZXJJZCI6NTQsImlhdCI6MTY0NjAzMzk3MSwianRpIjoiNTkiLCJzdWIiOiJhY2MxNDg3NzA1NCIsImV4cCI6MTY0NjI5MzE3MX0.E8_x87RtGIyAubBRO2nCAtwFzJgMi93_3APG1svQccubExZNWYw1Uoy6Va_xl-bOy1TmmX-taSTD_tkJP-jVzw

POST {{local}}/api/u/player/transferCoins
Authorization: {{token}}
Content-Type: application/json

{
    "targetPlayerMobilePhone":"18933934127",
    "number":111,
    "paymentPassword":"b123456"
}

###
post {{local}}/api/app/oauth/player/login
Content-Type: application/json

{
    "account":"15322315902",
    "password":"a123456_"
}

####
POST {{endpoint}}/api/app/oauth/player/register
Content-Type: application/json

{"name":"绘梨衣","phone":"15322315902","verifyCode":"15511",
"loginPassword":"a123456_","email":"754483487@qq.com","invitationCode":"2joquu","backupMobilePhone":"15322315902","paymentPassword":"b123456"}