@endpoint = http://repo.dev.smallsaas.cn:8084
@local = http://localhost:8080
@manage = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjoyLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDI2NTI4NTMsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MjkxMjA1M30._zoaYaPO5Zb_7KzdKSLpsg7RmR6YeiFUYaxkwOkdIqGRK2wW-k7niWpPh4b-ADFuv3TyM6gAshUhPnADn0Xuvw


### 查看实体状态流
# fromStatus  toStatus
GET {{endpoint}}/api/meta/entity/status/status
Authorization: {{manage}}

### 获取链式状态流
GET {{endpoint}}/api/meta/entity/status/status/linked

### 审批通过，创建日志保存工作流
POST {{local}}/api/meta/entity/status/entities/463/action/pass
Authorization: {{manage}}

{
  "note": "test1"
}

### 批量审批通过，创建日志保存工作流
POST {{endpoint}}/api/meta/entity/status/entities/action/bulk/pass

{
  "addition": {
    "note": "string"
  },
  "ids": [
    1,2
  ]
}

### 审批不通过，tode:创建日志保存工作流
POST {{local}}/api/crud/oms/player/reject/463
Authorization: {{manage}}

{
  "note": "绘梨衣1不通过"
}

### 获取工作流
GET {{endpoint}}/api/meta/workflow/entity/status/entities/1
Authorization: {{manage}}
