
@test = http://localhost:8080
@prod = http://webapp.metagugu.net


# 18689911298 123456
@player1 = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6MSwidXNlcklkIjoyNzcsImFjY291bnQiOiJhY2M4NzYxMDc1NCIsImRvbWFpblVzZXJJZCI6MzA4LCJpYXQiOjE2NDI1MTUxNTEsImp0aSI6IjI3NyIsInN1YiI6ImFjYzg3NjEwNzU0IiwiZXhwIjoxNjQyNzc0MzUxfQ.sLbUCr70prA5Prc7uhJYXv-4tsuUzs_BO53nU-2OEVuoN56qfPXestB9q2VTDK9lMpNocd9BnYxKpiu8u8KvZg
# 18689911295 a123456
@player2 = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6MTAsImFjY291bnQiOiJhY2M5NDA2NTAzMiIsImRvbWFpblVzZXJJZCI6OSwiaWF0IjoxNjQyNzM1MzQ3LCJqdGkiOiIxMCIsInN1YiI6ImFjYzk0MDY1MDMyIiwiZXhwIjoxNjQyOTk0NTQ3fQ.fks7TtQbkxprN_WB1TXy0Lp4yUgB8oegGwGCUQUa_3u4xfBEozizcPCEDp9u1tPwqZiwH_TCX8RCUpnyFSNJPQ
##
@man = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjoyLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDMwNzk0OTEsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MzMzODY5MX0.wgZ1RAFJjUi-2cWZXi3TZN201X-sIBDTP1n5VYP5-TdmaMDUhttwVDPQHNe7FqT1zuaM2wu3o-iPl52A_Why4w


### 发短信
POST {{prod}}/api/sms/v1/captcha

{
  "phone": "18689911298",
  "operation": "changeAccount"
}


### 玩家1登录
POST {{prod}}/api/app/oauth/player/login

{
    "account": "18689911298",
    "password": "123456"
}

### 玩家2登录
POST {{prod}}/api/app/oauth/player/login

{
    "account": "13800000008",
    "password": "a123456"
}
  

### 查询玩家信息
GET {{test}}/api/u/player
Authorization: {{player1}}


### 修改支付密码
PUT {{test}}/api/u/player
Authorization: {{man}}

{
    "paymentPassword":"123456"
}


### 查询成长中的精灵
GET {{test}}/api/u/player/queryPlayerWispInstance?stage=GROWING&pageSize=10&pageNum=1
Authorization: {{player2}}


### 精灵市场 
GET {{test}}/api/u/wisp/market
Authorization: {{player2}}


