@endpoint=http://api.dev.smallsaas.cn:8084

@player1= Bearer 
@admin= Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjoyLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDIyNjQzMTMsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MjUyMzUxM30.5KuCHFKMiUWvZQ5iiO4Ei5qNSz9_bIeldknx5_mdd3AgY18lcjpXshYhVkbGK0C1rWY0s0Jd1DetruV1lFbd3Q


##### 用户侧

### 签到
GET {{endpoint}}/api/u/sign
Authorization: {{player1}}

### 补签
POST  {{endpoint}}/api/u/sign/replenish
Authorization: {{player1}}

{
    "replenishSignDate": "2022-01-12"
}


### 列表
GET {{endpoint}}/api/u/sign?month=1&year=2022



##### 管理端

### 签到管理
GET {{endpoint}}/api/crud/oms/playerSignRecord/playerSignRecords
Authorization: {{admin}}
