@endpoint=http://localhost:8080
@local=http://localhost:8080

### 开启定时任务记录
GET {{endpoint}}/api/crud/schedule/recordScheduleRecord

###获取定时任务当天记录
GET {{endpoint}}/api/crud/schedule

###获取所有定时任务记录
GET {{endpoint}}/api/crud/schedule/allScheduleRecord
