@endpoint=http://localhost:8080
@local=http://localhost:8080
@admin = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDg0MzE4OTQsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0ODY5MTA5NH0.e6iAmvMy_PX43pRCpczxrFiCCg-TGGCNG26qYoTQmEQESMJlNqq9q0zuO4SryGGkg2q7bc5ig9DwlGpjuDwbHQ


### 开启定时任务记录
GET {{endpoint}}/api/crud/schedule/recordScheduleRecord

###获取定时任务当天记录
GET {{endpoint}}/api/crud/schedule

###获取所有定时任务记录
GET {{endpoint}}/api/crud/schedule/allScheduleRecord

###
GEt {{endpoint}}/api/crud/schedule/allJobAndRecord
Authorization: {{admin}}

###
GET {{endpoint}}/api/crud/oms/manager/managers/view/schedule?sessionId=2&_t=1648177629983&id=id&type=match
Authorization: {{admin}}

###
POST {{endpoint}}/api/crud/oms/marketingSession/marketingSessions/execute/4
Authorization: {{admin}}
