@endpoint=http://localhost:8080
@local=http://localhost:8080
@admin = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjAsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDgxNzQ0NjAsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0ODQzMzY2MH0.vHLQLTzUMNKXvOsFRiIABPLGgwdL5mYDVguf5tkIf3K0jYelh18kU6S3zotmoBkIJjsvaO1vqAmU8fvg3lu-0g


### 开启定时任务记录
GET {{endpoint}}/api/crud/schedule/recordScheduleRecord

###获取定时任务当天记录
GET {{endpoint}}/api/crud/schedule

###获取所有定时任务记录
GET {{endpoint}}/api/crud/schedule/allScheduleRecord

###
GEt {{endpoint}}/api/crud/schedule/allJobAndRecord
Authorization: {{admin}}

###
GET {{endpoint}}/api/crud/oms/manager/managers/view/schedule?sessionId=1&type=wispUp
Authorization: {{admin}}