@endpoint = http://repo.dev.smallsaas.cn:8084
@local = http://localhost:8080
@player1 = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6NzIwLCJhY2NvdW50IjoiYWNjMTcyMTE3NSIsImRvbWFpblVzZXJJZCI6NDYxLCJpYXQiOjE2NDMxNjg0NzYsImp0aSI6IjcyMCIsInN1YiI6ImFjYzE3MjExNzUiLCJleHAiOjE2NDM0Mjc2NzZ9.yH-cMzR1nHUUjJRv2d1Vf2xcCXOOmP8m-JHPh5xlKP13uwMjWrMFaW11zVHuO7FaRLbLcvDF-20LuUUdln5ydQ
@manage = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjoyLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDMwNzk0OTEsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MzMzODY5MX0.wgZ1RAFJjUi-2cWZXi3TZN201X-sIBDTP1n5VYP5-TdmaMDUhttwVDPQHNe7FqT1zuaM2wu3o-iPl52A_Why4w
@player2 = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6NjkwLCJhY2NvdW50IjoiYWNjNDI3OTM0NTYiLCJkb21haW5Vc2VySWQiOjQzMywiaWF0IjoxNjQzMTAyNzkyLCJqdGkiOiI2OTAiLCJzdWIiOiJhY2M0Mjc5MzQ1NiIsImV4cCI6MTY0MzM2MTk5Mn0.e9hrlJr_SXz6qeIbzC8RVR8NbjK2HF4XKGbPssowf3MD4OV3zrK9WM5DWccc8gavho8HP0dfpsi-ltr9l4THzQ
@player1 = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6NzIwLCJhY2NvdW50IjoiYWNjMTcyMTE3NSIsImRvbWFpblVzZXJJZCI6NDYxLCJpYXQiOjE2NDMxNzMzNzksImp0aSI6IjcyMCIsInN1YiI6ImFjYzE3MjExNzUiLCJleHAiOjE2NDM0MzI1Nzl9.3eXYkV8DaF2sF4rGcRHK7RZx36LruCUgUy1Io-hOAOJ8UFCpBIha07VE5lLh-C9OBJ8kd5HnpJXce15E5CT1lA
@manage = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjoyLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDI0MDcxNjQsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MjY2NjM2NH0.wKNsgYU01donb0fjhD8PZJJvVKnY2ziqvuo7UvWGjphyqaH7fWin2tD2Oqb40-6XsKQAEN0EdWMIn_VWO4hyNw

@token = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6MjEsImFjY291bnQiOiJhY2M4NDg3MjM5MCIsImRvbWFpblVzZXJJZCI6MjAsImlhdCI6MTY0NDU0NjkwNiwianRpIjoiMjEiLCJzdWIiOiJhY2M4NDg3MjM5MCIsImV4cCI6MTY0NDgwNjEwNn0.o2wlInag-vsZEUjgkrOXrzWBDtiE9HiffM-NXNZxfEtmumoowPcAbBtU7cPK7Im0SHB2akPinF43fFdRys6EwQ

### 查看精灵详情
GET {{local}}/api/crud/oms/wisp/wisps/54
Authorization: {{manage}}

### 添加精灵
POST {{endpoint}}/api/crud/oms/wisp/wisps
Authorization: {{manage}}

{
  "costAccompanyWisp": 1,
  "costLand": 1,
  "costWispCoin": 1,
  "description": "1",
  "growthDays": 1,
  "growthPercent": 1,
  "level": 1,
  "maximumValue": 100,
  "metaId": 1,
  "minimumValue": 1,
  "name": "1",
  "previewPhotoUrl": "1",
  "sessionId": 1,
  "waitingMatchMinute": 1
}

### 根据名称查询
GET {{local}}/api/crud/oms/wisp/wisps?name=龙
Authorization: {{player1}}

### 新增精灵
POST {{local}}/api/crud/oms/wisp/wisps
Authorization: {{player1}}

{
"costAccompanyWisp": 213,
"costWispCoin": 123,
"description": "123",
"endMatchTime": "11:04:00",
"growthDays": 123,
"growthPercent": 123,
"level": 1,
"maximumValue": 123,
"minimumValue": 123,
"name": "花仙子1",
"startMatchTime": "11:04:00",
"waitingMatchMinute": 123
}

### 新增店小二
POST {{local}}/api/crud/oms/manager/managers

{
    "invitationCode": "1",
    "mobilePhone": 1,
    "name": "1",
    "paymentPassword": "1"
}

### 场次管理
POST {{local}}/api/crud/oms/marketingSession/marketingSessions

{
    "endTime": "08:00:00",
    "number": "1",
    "startTime": "08:00:00",
    "title": "1"
}

### 玩家查询
GET {{local}}/api/crud/oms/player/players
Authorization: {{player1}}


### 精灵市场列表
GET {{local}}/api/u/wisp/market
Authorization: {{player1}}

### 查看精灵列表
GET {{local}}/api/crud/oms/wisp/wisps
Authorization: {{manage}}


### 发放精灵币
POST {{local}}/api/crud/oms/manager/managers/sendCoins
Authorization: {{manage}}

{
"targetPlayerMobilePhone":15322315902,
"number":10,
"paymentPassword":"123456"
}


### 根据玩家身份查询订单信息
GET {{local}}/api/u/order/wisp
Authorization: {{player1}}




### 团队未付款
GET {{local}}/api/u/player/getUnpaidTeamUserById
Authorization: {{player1}}


### 店小二发放精灵币查询
GET {{endpoint}}/api/crud/oms/manager/managers/queryManagerGivenPlayerCoins
Authorization: {{manage}}

### 店小二发放精灵币查询
GET {{local}}/api/crud/oms/manager/managers/queryManagerGivenPlayerCoins
Authorization: {{token}}


### 店小二发放精灵币查询
GET {{local}}/api/crud/oms/manager/managers/queryManagerGivenPlayerCoins?adminPlayerId=1
Authorization: {{token}}

### 店小二发放精灵币查询
GET {{local}}/api/crud/oms/manager/managers/queryManagerGivenPlayerCoins?sysPlayerId=10
Authorization: {{token}}

### 店小二发放精灵币查询
GET {{local}}/api/crud/oms/manager/managers/queryManagerGivenPlayerCoins?adminPlayerId=1&sysPlayerId=10
Authorization: {{token}}



### 店小二发放精灵币查询
GET {{local}}/api/crud/oms/manager/managers/queryManagerGivenPlayerCoins?&sysPlayerId=461
Authorization: {{token}}


### 店小二发放精灵币查询
GET {{local}}/api/crud/oms/manager/managers/queryManagerGivenPlayerCoins?&recipientHint=花落一世界
Authorization: {{token}}



### 店小二发放精灵币查询
GET {{local}}/api/crud/oms/manager/managers/queryManagerGivenPlayerCoins?&startDate=2022-01-11&endDate=2022-01-11
Authorization: {{token}}


### 店小二发放精灵币查询
GET {{local}}/api/crud/oms/manager/managers/queryManagerGivenPlayerCoins?&startDate=2022-01-22&endDate=2022-01-22
Authorization: {{token}}



### 店小二发放精灵币查询
GET {{local}}/api/crud/oms/manager/managers/queryManagerGivenPlayerCoins?&sysPlayerId=461&startDate=2022-01-22&endDate=2022-01-22
Authorization: {{token}}



### 根据手机号、邀请码、名称查询玩家
GET {{local}}/api/crud/oms/player/players?search=路明非
Authorization: {{manage}}

### 玩家查询 ismanage
GET  {{local}}/api/crud/oms/player/players
Authorization: {{manage}}


### 新建玩家
POST {{local}}/api/crud/oms/player/players
Authorization: {{manage}}

{
  "alipayAccount": "贝吉塔",
  "alipayQrCodePhotoUrl": "string",
  "backupMobilePhone": "15322315905",
  "backupMobilePhoneCode": "15322315905",
  "bankAccountName": "贝吉塔",
  "bankAccountName2": "贝吉塔",
  "bankAccountNumber": "15322315905",
  "bankAccountNumber2": "15322315905",
  "bankName": "贝吉塔",
  "bankName2": "贝吉塔",
  "email": "84919848@qq.com",
  "frontIdCardPhotoUrl": "string",
  "invitationCode": "iiwos3",
  "isManager": 0,
  "loginPassword": "admin123",
  "mobilePhone": "15322315905",
  "mobilePhoneCode": "15322315905",
  "name": "贝吉塔",
  "paymentPassword": "admin123",
  "reverseSideIdCardPhotoUrl": "string",
  "wechatAccount": "string",
  "wechatQrCodePhotoUrl": "string"
}

{
  "paymentPassword":"123456"
}

### 查看预约记录
GET {{local}}/api/u/player/record/book?onlyCurrentDay=0
Authorization: {{player1}}

### 申请解冻
POST {{local}}/api/u/player/unlock
Authorization: {{player1}}

{
  "paymentPassword":"admin123456"
}

### 获取买家精灵订单列表信息
GET {{local}}/api/u/order/wisp/buy?onlyCurrentDay=0
Authorization: {{player1}}

### 获取未付款列表
GET {{endpoint}}/api/u/order/wisp/count/unpaid
Authorization: {{player1}}


### 获取卖家精灵订单列表信息
GET https://www.metagugu.net/api/u/order/wisp/record/sell
Authorization: 