@endpoint = http://repo.dev.smallsaas.cn:8084
@meta = http://www.metagugu.net
@local = http://localhost:8080
@player1 = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6NzAzLCJhY2NvdW50IjoiYWNjMTk3MDY3NzkiLCJkb21haW5Vc2VySWQiOjQ0NCwiaWF0IjoxNjQyNjY0NjQyLCJqdGkiOiI3MDMiLCJzdWIiOiJhY2MxOTcwNjc3OSIsImV4cCI6MTY0MjkyMzg0Mn0.7g5pArAkfoo4w_4L-R2pV86a310uN-qU5zgOlsrIdnYtIPQGBaqkf1Bs9T1bdho2B6g32gyIJ88q5Qs6sF8_Mw
@manage1 = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjoyLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDI2NDM2NzEsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MjkwMjg3MX0.Ry7YAuLmjcE-ftWRq705Os24bkRZP69LrS3uD53RE2q_C4UHsqJ_Cb-QgiGh5e0DXu3cU9C93gHrV0hZKO_b3w
@huiliyi = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6MSwidXNlcklkIjo1OTcsImFjY291bnQiOiJhY2MxMzM0MTc3MCIsImRvbWFpblVzZXJJZCI6Mzc3LCJpYXQiOjE2NDIwNDYwMjcsImp0aSI6IjU5NyIsInN1YiI6ImFjYzEzMzQxNzcwIiwiZXhwIjoxNjQyMzA1MjI3fQ.g2Je444UNcgOYTNvdisA01hMqji9hZK39xWD997g8005Wb-Mh7rwa8XjhLFu_Ds6vtR9cMn9vSUJzoxKfP03HA
@chuzihang = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6MSwidXNlcklkIjo1OTgsImFjY291bnQiOiJhY2M5NDExNzA3MCIsImRvbWFpblVzZXJJZCI6Mzc4LCJpYXQiOjE2NDIwNDYwNTYsImp0aSI6IjU5OCIsInN1YiI6ImFjYzk0MTE3MDcwIiwiZXhwIjoxNjQyMzA1MjU2fQ.9lGy-J1trHHqiWceIy5W4lHz2cf2FPfJiNR3HPL1C4wN5BhTn_KTGsx_RJcDlBODeZTk4gBhaKvqoKSVpmdWkA

## 18689911295 123456
@metatester= Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6MjgwLCJhY2NvdW50IjoiYWNjNjkwMjg3NTUiLCJkb21haW5Vc2VySWQiOjMxMSwiaWF0IjoxNjQyMzAyMDQ0LCJqdGkiOiIyODAiLCJzdWIiOiJhY2M2OTAyODc1NSIsImV4cCI6MTY0MjU2MTI0NH0.2kUciqoE5cf1Hm5IxI1V3GJZiUUVMD2tM7Af_5Boj1ftnbIJmrBLhyr6ATk3Yw_s8wbl43N3lR0E5EL0LZJULg


@token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDQzOTQxMzcsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0NDY1MzMzN30.JpRY5WCVLaXoMgvmb7MMCdboocS80lQguRqZiLueqk-jbJ9CCET-CrgDmBT-G91axGYZtNBi-YzwuPPwoV7dLA

### 预约精灵
POST {{meta}}/api/u/wisp/31/book
Authorization: {{metatester}}

{
  "paymentPassword": "123456"
}


### 精灵市场列表
GET {{local}}/api/u/wisp/market
Authorization: {{player1}}

### 店小二定向发放精灵币
POST {{local}}/api/crud/oms/manager/managers/sendCoins
Authorization: {{manage1}}

{
  "number": 100,
  "paymentPassword": "admin",
  "targetPlayerMobilePhone": 13800000000
}

### 购买陪伴精灵
POST {{endpoint}}/api/u/companionWisp/1/buy
Authorization: {{player1}}

{
  "companionWispId": 1,
  "number": 10,
  "paymentPassword": "123456"
}

### 查看玩家资源
GET {{endpoint}}/api/u/player/wallet
Authorization: {{player1}}

### 查看陪伴精灵
GET {{endpoint}}/api/crud/oms/companionWisp/companionWisps
Authorization: {{manage1}}

### 查看土地信息
GET {{endpoint}}/api/crud/oms/land/lands
Authorization: {{manage1}}

### 租用土地
POST {{endpoint}}/api/u/land/1/buy
Authorization: {{chuzihang}}

{
  "paymentPassword": "123456",
  "purchaseQuantity": 50
}

### 查看玩家资源
GET {{endpoint}}/api/u/player/wallet
Authorization: {{player1}}

### 预约精灵
POST {{endpoint}}/api/u/wisp/12/book
Authorization: {{player1}}

{
  "paymentPassword": "123456"
}

### 查看预约精灵记录
# GET {{endpoint}}/api/crud/oms/wispBookingRecord/wispBookingRecords
GET {{local}}/api/crud/oms/wispBookingRecord/wispBookingRecords
Authorization: {{manage1}}

### 查看预约精灵记录：给定玩家名
# GET {{endpoint}}/api/crud/oms/wispBookingRecord/wispBookingRecords?playerName=小可爱
GET {{local}}/api/crud/oms/wispBookingRecord/wispBookingRecords?playerName=小可爱
Authorization: {{manage1}}

### 查看预约精灵记录：给定挂售场次
GET {{local}}/api/crud/oms/wispBookingRecord/wispBookingRecords?account=10
Authorization: {{manage1}}


### 查看预约精灵记录：给定玩家名和场次
# GET {{endpoint}}/api/crud/oms/wispBookingRecord/wispBookingRecords?playerName=小可爱
GET {{local}}/api/crud/oms/wispBookingRecord/wispBookingRecords?playerName=小可爱&account=10
Authorization: {{manage1}}

### 查看预约精灵记录：给定玩家名和场次
# GET {{endpoint}}/api/crud/oms/wispBookingRecord/wispBookingRecords?playerName=小可爱
GET {{local}}/api/crud/oms/wispBookingRecord/wispBookingRecords?playerName=小可爱&account=5
Authorization: {{manage1}}

### 精灵市场列表
GET {{local}}/api/u/wisp/market
Authorization: {{player1}}


### 根据挂售场次查询精灵列表
GET {{endpoint}}/api/crud/oms/wisp/wisps/getWispListWithStatisticsByMarketingSessionId
Authorization: {{manage1}}



### 根据挂售场次查询精灵列表
GET {{local}}/api/crud/oms/wisp/wisps/getWispListWithStatisticsByMarketingSessionId
Authorization: {{manage1}}


### 根据挂售场次查询精灵列表
GET {{local}}/api/crud/oms/wisp/wisps/getWispListWithStatisticsByMarketingSessionId
Authorization: {{token}}

### 根据挂售场次查询精灵列表
GET {{local}}/api/crud/oms/wisp/wisps/getWispListWithStatisticsByMarketingSessionId?sessionId=1
Authorization: {{token}}

### 根据挂售场次查询精灵列表
GET {{local}}/api/crud/oms/wisp/wisps/getWispListWithStatisticsByMarketingSessionId?sysNumber=1475737676417097737
Authorization: {{manage1}}

### 根据挂售场次查询精灵列表
GET {{local}}/api/crud/oms/wisp/wisps/getWispListWithStatisticsByMarketingSessionId?startDate=2022-01-20&endDate=2022-02-01
Authorization: {{token}}


### 根据挂售场次查询精灵列表
GET {{local}}/api/crud/oms/wisp/wisps/getWispListWithStatisticsByMarketingSessionId?sessionId=1&startDate=2022-02-08&endDate=2022-02-08
Authorization: {{token}}


### 根据玩家状态查询
GET {{local}}/api/crud/oms/player/players?playerStatus=FROZEN
Authorization: {{manage1}}
