@endpoint = http://repo.dev.smallsaas.cn:8084
@local = http://localhost:8080
@player1 = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6MTIzLCJhY2NvdW50IjoiYWNjMjg4MTY1NTAiLCJkb21haW5Vc2VySWQiOjY4LCJpYXQiOjE2NDA3NzA0NTIsImp0aSI6IjEyMyIsInN1YiI6ImFjYzI4ODE2NTUwIiwiZXhwIjoxNjQxMDI5NjUyfQ.rBJqopdLHe7WjLayJW28b9iPWwLhxqPQDkdMy1gDmZMmgpflqGXY6b3EfqCuObSzSrBcgTZkZvdfpGa5nFF-mA
@manage1 = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDEyODc3MDUsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MTU0NjkwNX0.R1-Tzyx1qrPXvzbC8V5f5DYb0sSo4HapeUw9Sl9TmVjzC1vQU-H04fgT2Cq6qdax9jsoIh-XLrTfZYmQR8xW5Q

@admin = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjoyLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDI1NjI3MjYsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MjgyMTkyNn0.ZVh6t8BKQmmNS54aQsuPLhhlxgMUUY-MNNozZpCsat3VJqBPZaDhlyTABwoYW7Khn2h-bo2whIKIPqdzubQBAA

### 新增精灵
POST {{local}}/api/crud/oms/wisp/wisps
Authorization: {{manage1}}

{
  "costAccompanyWisp": 50,
  "costWispCoin": 50,
  "description": "龙王",
  "growthDays": 3,
  "growthPercent": 30,
  "level": 5,
  "maximumValue": 100,
  "metaId": 3,
  "minimumValue": 80,
  "name": "🐉白王",
  "previewPhotoUrl": "https://s2.loli.net/2021/12/20/WPKatHfhmSsdQuF.jpg",
  "sessionId": 1,
  "waitingMatchMinute": 30
}

### 生产环境创建精灵问题  "Field 'start_match_time' doesn't have a default value"
POST {{local}}/api/crud/oms/wisp/wisps
Authorization: {{admin}}

{
    "metaId": "31",
    "name": "HKL",
    "description": "HKL",
    "sessionId": "30",
    "previewPhotoUrl": [
        {
            "url": "/images//1cf765cd-6cb5-45d8-a52d-1d6e9fc2a279.jpg"
        },
        {
            "url": "/images//3c186468-5a45-494b-a593-959ff9d3fc02.jpg"
        }
    ],
    "level": 2,
    "minimumValue": 300,
    "maximumValue": 600,
    "growthDays": 3,
    "growthPercent": 6,
    "costWispCoin": 50,
    "costAccompanyWisp": 5,
    "waitingMatchMinute": 30
}



### 修改
PUT {{local}}/api/crud/oms/wisp/wisps/65
Authorization: {{manage1}}

{
  "costAccompanyWisp": 50,
  "costWispCoin": 50,
  "description": "龙王",
  "growthDays": 3,
  "growthPercent": 30,
  "level": 5,
  "maximumValue": 100,
  "metaId": 3,
  "minimumValue": 80,
  "name": "🐉白王",
  "previewPhotoUrl": "https://s2.loli.net/2021/12/20/WPKatHfhmSsdQuF.jpg",
  "sessionId": 1,
  "waitingMatchMinute": 30
}

### 查看精灵
GET {{local}}/api/crud/oms/wisp/wisps
Authorization: {{manage1}}