@endpoint = http://repo.dev.smallsaas.cn:8084
@local = http://localhost:8080
@player1 = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwiYWNjb3VudCI6ImFkbWluIiwiaWF0IjoxNjM5MjE0Mzg5LCJqdGkiOiIxIiwic3ViIjoiYWRtaW4iLCJleHAiOjE2NDE4MDYzODl9.yh64lfxDjd-OC-33zmqUmHl7JeGmIDRukdAvvZiMfAGk1ZjLumSDmjaRClquTlytSMb5exoBCncQ0joKs-46DQ

### 精灵市场列表
GET {{endpoint}}/api/crud/oms/wisp/wisps/market
Authorization: {{player1}}

### 精灵订单记录列表信息
GET {{local}}/api/crud/oms/companionWispOrder/companionWispOrders
Authorization: {{player1}}

### 购买陪伴精灵
POST {{local}}/api/crud/oms/companionWispOrder/companionWispOrders/generate
Authorization: {{player1}}

{
  "companionWispId": 2,
  "number": 1,
  "paymentPassword": "123456"
}

### 查看陪伴精灵
GET {{local}}/api/crud/oms/companionWisp/companionWisps/2
Authorization: {{player1}}

### 查看土地信息
GET {{local}}/api/crud/oms/land/lands
Authorization: {{player1}}

### 租用土地
POST {{local}}/api/crud/oms/land/lands/1/buy
Authorization: {{player1}}

{
  "paymentPassword": "123456",
  "purchaseQuantity": 1
}

### 预约精灵
POST {{local}}/api/crud/oms/wisp/wisps/2/book
Authorization: {{player1}}

{
  "paymentPassword": "123456"
}


### 查看预约精灵记录
GET {{endpoint}}/api/crud/oms/wispBookingRecord/wispBookingRecords
Authorization: {{player1}}


### 精灵市场列表
GET {{endpoint}}/api/crud/oms/wisp/wisps/market
Authorization: {{player1}}

### 查看元精灵详情
GET {{local}}/api/crud/oms/wispMeta/wispMetas/1
Authorization: {{player1}}

### 查看元精灵
GET {{local}}/api/crud/oms/wispMeta/wispMetas
Authorization: {{player1}}
