@endpoint = http://repo.dev.smallsaas.cn:8084
@local = http://localhost:8080
@player1 = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6MTA4LCJhY2NvdW50IjoiYWNjMjY3NzUzNjEiLCJkb21haW5Vc2VySWQiOjUzLCJpYXQiOjE2NDA1OTgyMjQsImp0aSI6IjEwOCIsInN1YiI6ImFjYzI2Nzc1MzYxIiwiZXhwIjoxNjQwODU3NDI0fQ.TLqA3IDqDruGzSwELr0yHc2nG0hpCL_wZ_Knx8fUn4oA--3k7U2tEmRxcKKLLqT_IoiiIcTqbJFTxGz60j6nDg
@manage1 = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidXNlclR5cGUiOjEwMSwiYlVzZXJUeXBlIjoiU1lTVEVNIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsImV4dHJhVXNlclR5cGUiOjAsImlhdCI6MTY0MDY3NDA5OCwianRpIjoiMSIsInN1YiI6ImFkbWluIiwiZXhwIjoxNjQwOTMzMjk4fQ.dArsApkrrtbQzY9Cir9FX3uLceimDK9ZrR_F2F0Cf0EJIGIECelHIU23ywRl-VcxALbnP0hHlf76fk4cJ2aVhg

